### PR TITLE
Mention that OpenSSL is required

### PR DESCRIPTION
**Pull request by kirs**
@nathanaeljones

### CODE REVIEW

**Comment by nathanaeljones** [comment]
Thanks! Please let me know if you encounter any other pain points during the build.

**Comment by nathanaeljones** [comment]
Also, which tool are you trying to build/use? Things are quite a mess right now, although they should get a little better in a few hours.

**Comment by kirs** [comment]
I've been trying to build all of imageflow and play with it. I tried the CLI and server parts.

So far I could not run the ruby wrapper because it could not file `build/imageflow.so`. Is it supposed to be there?

**Comment by nathanaeljones** [comment]
The ruby wrapper is out of date; we've since refactored the FFI API to use JSON, but the JSON API doesn't yet have full parity. Once that lands, then I'll update the ruby wrapper.

**Comment by nathanaeljones** [comment]
Functionality-wise, this is a low point for the project, due to the refactoring and porting process. It should accelerate again pretty soon. flow-proto1 is probably the only useful tool present.

**Pull request merged**
